name: CPU CI, CUDA/HIP build CI

on:
  push:
    branches: [ main, 'pr/*' ]
  pull_request:
    branches: [ main ]

jobs:

  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        extensions: 'h,cxx'
        clangFormatVersion: 9
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        extensions: 'h,cxx'
        clangFormatVersion: 14

  tests-cpu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cxx: [ 'g++-7', 'g++-9', 'clang++-9' ]
    name: tests-cpu-${{ matrix.cxx }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build-tests-${{ matrix.cxx }} -DGTENSOR_DEVICE=host -DCMAKE_BUILD_TYPE=RelWithDebInfo
      env:
        CXX: ${{ matrix.cxx }}
    - name: build
      run: cmake --build build-tests-${{ matrix.cxx }} -v
    - name: test
      run: cmake --build build-tests-${{ matrix.cxx }} -t test

  tests-cpu-cxx20:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [ 'g++-12', 'clang++-14' ]
    name: tests-cpu-cxx20-${{ matrix.cxx }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build-tests-${{ matrix.cxx }} -DGTENSOR_DEVICE=host -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=20
      env:
        CXX: ${{ matrix.cxx }}
    - name: build
      run: cmake --build build-tests-${{ matrix.cxx }} -v
    - name: test
      run: cmake --build build-tests-${{ matrix.cxx }} -t test

  examples-cpu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cxx: [ 'g++-7', 'g++-9', 'clang++-9' ]
    name: examples-cpu-${{ matrix.cxx }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build-examples-${{ matrix.cxx }} -DGTENSOR_DEVICE=host -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTENSOR_BUILD_EXAMPLES=ON -DBUILD_TESTING=OFF -DGTENSOR_ENABLE_CLIB=ON
      env:
        CXX: ${{ matrix.cxx }}
    - name: build
      run: cmake --build build-examples-${{ matrix.cxx }} -v
    - name: daxpy
      run: ./build-examples-${{ matrix.cxx }}/examples/daxpy
    - name: stencil1d
      run: ./build-examples-${{ matrix.cxx }}/examples/stencil1d
    - name: mult_table
      run: ./build-examples-${{ matrix.cxx }}/examples/mult_table

  examples-cpu-ub:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [ 'clang++-14' ]
    name: examples-cpu-ub-${{ matrix.cxx }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build-examples-ub-${{ matrix.cxx }} -DGTENSOR_DEVICE=host -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTENSOR_BUILD_EXAMPLES=ON -DBUILD_TESTING=OFF -DGTENSOR_ENABLE_CLIB=ON -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O1 -g -fsanitize=address,undefined,implicit-conversion,integer,nullability -fno-sanitize-recover=address,undefined,implicit-conversion,integer,nullability -fno-omit-frame-pointer -fno-optimize-sibling-calls"
      env:
        CXX: ${{ matrix.cxx }}
    - name: build
      run: cmake --build build-examples-ub-${{ matrix.cxx }} -v
    - name: daxpy
      run: ./build-examples-ub-${{ matrix.cxx }}/examples/daxpy
    - name: stencil1d
      run: ./build-examples-ub-${{ matrix.cxx }}/examples/stencil1d
    - name: mult_table
      run: ./build-examples-ub-${{ matrix.cxx }}/examples/mult_table

  examples-cpu-gnu-make:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: setup gtensor subdir
      run: mkdir -p external/gtensor &&  cp -R ../include external/gtensor/
      working-directory: ${{ github.workspace }}/examples
    - name: build
      run: make GTENSOR_DEVICE=host
      working-directory: ${{ github.workspace }}/examples
    - name: daxpy
      run: ./daxpy
      working-directory: ${{ github.workspace }}/examples
    - name: stencil1d
      run: ./stencil1d
      working-directory: ${{ github.workspace }}/examples
    - name: mult_table
      run: ./mult_table
      working-directory: ${{ github.workspace }}/examples


  cmake-subdir:
    runs-on: ubuntu-latest
    env:
      cxx: 'clang++-9'
      CMAKE_BUILD_PARALLEL_LEVEL: 8
    defaults:
      run:
        working-directory: ${{ github.workspace }}/examples

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build-subdir -DGTENSOR_DEVICE=host -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: build
      run: cmake --build build-subdir -v
    - name: daxpy
      run: ./build-subdir/daxpy
    - name: stencil1d
      run: ./build-subdir/stencil1d
    - name: mult_table
      run: ./build-subdir/mult_table


  cmake-install:
    runs-on: ubuntu-latest
    env:
      cxx: 'clang++-9'
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: gtensor cmake
      run: cmake -S . -B build-install -DGTENSOR_DEVICE=host -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/gtensor-install -DBUILD_TESTING=OFF -DGTENSOR_ENABLE_FORTRAN=ON
    - name: gtensor install
      run: cmake --build build-install -v -t install
    - name: examples cmake
      run: cmake -S . -B build-find-package -DGTENSOR_DEVICE=host -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTENSOR_EXAMPLES_USE_FIND_PACKAGE=ON -DGTENSOR_ENABLE_CLIB=ON -DGTENSOR_ENABLE_FORTRAN=ON
      working-directory: ${{ github.workspace }}/examples
      env:
        gtensor_DIR: ${{ github.workspace }}/gtensor-install
    - name: examples build
      run: cmake --build build-find-package -v
      working-directory: ${{ github.workspace }}/examples
    - name: daxpy
      run: ./build-find-package/daxpy
      working-directory: ${{ github.workspace }}/examples
    - name: stencil1d
      run: ./build-find-package/stencil1d
      working-directory: ${{ github.workspace }}/examples
    - name: mult_table
      run: ./build-find-package/mult_table
      working-directory: ${{ github.workspace }}/examples


  build-cuda:
    runs-on: ubuntu-latest
    container: nvidia/cuda:10.2-devel-ubuntu18.04
    env:
      GTEST_VERSION: 1.10.0
      GTEST_ROOT: ${{ github.workspace }}/googletest
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: apt-get update && apt-get install -y wget git
    - name: install cmake
      run: |
        wget -O cmake.sh 'https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.sh'
        bash cmake.sh --prefix=/usr --skip-license --exclude-subdir
    - name: install googletest
      run: |
        mkdir -p ${{ env.GTEST_ROOT }}
        cd ${{ env.GTEST_ROOT }}
        wget https://github.com/google/googletest/archive/release-${{ env.GTEST_VERSION }}.tar.gz
        tar xzf release-${{ env.GTEST_VERSION }}.tar.gz
        cmake -S googletest-release-${{ env.GTEST_VERSION }} -B build -DCMAKE_INSTALL_PREFIX=${{ env.GTEST_ROOT }}
        cmake --build build -t install
      env:
        CXX: g++-7
    - name: cmake thrust
      run: cmake -S . -B build-cuda -DGTENSOR_DEVICE=cuda -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTENSOR_BUILD_EXAMPLES=ON -DGTENSOR_USE_THRUST=ON -DGTEST_ROOT=${{ env.GTEST_ROOT }} -DGTENSOR_ENABLE_CLIB=ON -DGTENSOR_ENABLE_BLAS=ON -DGTENSOR_ENABLE_FFT=ON -DGTENSOR_ENABLE_SOLVER=ON
    - name: cmake thrust build
      run: cmake --build build-cuda -v
    - name: cmake thrust debug
      run: cmake -S . -B build-cuda-debug -DGTENSOR_DEVICE=cuda -DCMAKE_BUILD_TYPE=Debug -DGTENSOR_BUILD_EXAMPLES=ON -DGTENSOR_USE_THRUST=ON -DGTEST_ROOT=${{ env.GTEST_ROOT }} -DGTENSOR_ENABLE_CLIB=ON -DGTENSOR_ENABLE_BLAS=ON -DGTENSOR_ENABLE_FFT=ON -DGTENSOR_ENABLE_SOLVER=ON
    - name: cmake thrust debug build
      run: cmake --build build-cuda-debug -v
    - name: cmake nothrust
      run: cmake -S . -B build-cuda-nothrust -DGTENSOR_DEVICE=cuda -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTENSOR_BUILD_EXAMPLES=ON -DGTENSOR_USE_THRUST=OFF -DGTEST_ROOT=${{ env.GTEST_ROOT }} -DGTENSOR_ENABLE_CLIB=ON -DGTENSOR_ENABLE_BLAS=ON -DGTENSOR_ENABLE_FFT=ON -DGTENSOR_ENABLE_SOLVER=ON
    - name: cmake nothrust build
      run: cmake --build build-cuda-nothrust -v
    - name: GNU make setup gtensor subdir
      run: mkdir -p external/gtensor &&  cp -R ../include external/gtensor/
      working-directory: ${{ github.workspace }}/examples
    - name: GNU make build
      run: make GTENSOR_DEVICE=cuda
      working-directory: ${{ github.workspace }}/examples


  build-hip:
    runs-on: ubuntu-latest
    container: rocm/dev-ubuntu-22.04:5.4.2-complete
    env:
      CMAKE_PREFIX_PATH: /opt/rocm/lib/cmake
      CXX: /opt/rocm/bin/hipcc
      HCC_AMDGPU_TARGET: gfx90a
      GTEST_VERSION: 1.12.1
      GTEST_ROOT: ${{ github.workspace }}/googletest
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
    - uses: actions/checkout@v2
    - name: install core packages
      run: apt-get update -y && apt-get install -y wget git cmake clang
    - name: install extra ROCm packages
      run: apt-get install -y rocthrust rocprim rocfft rocblas hipfft rocsolver rocsparse
    - name: install googletest
      run: |
        mkdir -p ${{ env.GTEST_ROOT }}
        cd ${{ env.GTEST_ROOT }}
        wget https://github.com/google/googletest/archive/release-${{ env.GTEST_VERSION }}.tar.gz
        tar xzf release-${{ env.GTEST_VERSION }}.tar.gz
        cmake -S googletest-release-${{ env.GTEST_VERSION }} -B build -DCMAKE_INSTALL_PREFIX=${{ env.GTEST_ROOT }}
        cmake --build build -t install
      env:
        CXX: clang++
    - name: cmake thrust
      run: cmake -S . -B build-hip -DGTENSOR_DEVICE=hip -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTENSOR_BUILD_EXAMPLES=ON -DGTENSOR_USE_THRUST=ON -DGTEST_ROOT=${{ env.GTEST_ROOT }} -DGTENSOR_ENABLE_CLIB=ON -DGTENSOR_ENABLE_BLAS=ON -DGTENSOR_ENABLE_FFT=ON -DGTENSOR_ENABLE_SOLVER=ON
    - name: cmake thrust build
      run: cmake --build build-hip -v
    - name: cmake thrust debug
      run: cmake -S . -B build-hip-debug -DGTENSOR_DEVICE=hip -DCMAKE_BUILD_TYPE=Debug -DGTENSOR_BUILD_EXAMPLES=ON -DGTENSOR_USE_THRUST=ON -DGTEST_ROOT=${{ env.GTEST_ROOT }} -DGTENSOR_ENABLE_CLIB=ON -DGTENSOR_ENABLE_BLAS=ON -DGTENSOR_ENABLE_FFT=ON -DGTENSOR_ENABLE_SOLVER=ON
    - name: cmake thrust debug build
      run: cmake --build build-hip-debug -v
    - name: cmake nothrust
      run: cmake -S . -B build-hip-nothrust -DGTENSOR_DEVICE=hip -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTENSOR_BUILD_EXAMPLES=ON -DGTENSOR_USE_THRUST=OFF -DGTEST_ROOT=${{ env.GTEST_ROOT }} -DGTENSOR_ENABLE_CLIB=ON -DGTENSOR_ENABLE_BLAS=ON -DGTENSOR_ENABLE_FFT=ON -DGTENSOR_ENABLE_SOLVER=ON
    - name: cmake nothrust build
      run: cmake --build build-hip-nothrust -v
    - name: GNU make setup gtensor subdir
      run: mkdir -p external/gtensor &&  cp -R ../include external/gtensor/
      working-directory: ${{ github.workspace }}/examples
    - name: GNU make build
      run: make GTENSOR_DEVICE=hip
      working-directory: ${{ github.workspace }}/examples
